// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AngularTools
{
    internal sealed partial class Vsix
    {
        public const string Id = "AngularTools.1ddcbd14-b2ef-4ba0-bff8-d2b27660b977";
        public const string Name = "AngularTools";
        public const string Description = @"# Angular Tools for Visual Studio 2022 (WIP)

**Angular Tools** is a Visual Studio extension designed to streamline Angular development. It provides a set of productivity-enhancing commands and features tailored for Angular projects, making your workflow faster and more efficient.

## Features

1. **Rename Angular Component**  
   Easily rename Angular components, including their associated files (`.ts`, `.html`, `.scss`, `.spec.ts`) and references across the project.

*`Edit > Rename Angular Component`*

2. **Switch Between `.ts` and `.html` Files**  
   Quickly toggle between `.ts` and `.html`.

*`Tools > Switch Between .ts/html` or `[shortcut Ctrl + 2]`*

3. **Switch Between `.scss` and `.html` Files**  
   Quickly toggle between `.scss` and `.html`.

*`Tools > Switch Between .scss/.html` or `[shortcut Ctrl + 3]`*

4. **Open Console in Project Directory**  
   Open a terminal directly in the current project directory for quick access to Angular CLI commands.

*`Tools > Open Console Here` or `[shortcut Ctrl + 4]`*

## License

This project is licensed under the [MIT License](LICENSE).
";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Krystian Skwierawski";
        public const string Tags = "Visual Studio, Angular, Tools, Extension";
    }
}
