// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AngularTools
{
    internal sealed partial class Vsix
    {
        public const string Id = "AngularTools.1ddcbd14-b2ef-4ba0-bff8-d2b27660b977";
        public const string Name = "AngularTools";
        public const string Description = @"Visual Studio extension designed to streamline Angular development. It provides a set of productivity-enhancing commands and features tailored for Angular projects, making your workflow faster and more efficient.
        ";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Krystian Skwierawski";
        public const string Tags = "Visual Studio, Angular, Tools, Extension";
    }
}
