// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AngularTools
{
    internal sealed partial class Vsix
    {
        public const string Id = "AngularTools.1ddcbd14-b2ef-4ba0-bff8-d2b27660b977";
        public const string Name = "AngularTools";
        public const string Description = @"AngularToolsAngu";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "bezi25251@gmail.com";
        public const string Tags = "";
    }
}
